services:
  nginx:
    image: nginx:alpine
    container_name: smartvillage-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend-build:/usr/share/nginx/html:ro
      - /opt/smartvillage/certs:/etc/nginx/certs:ro
    networks:
      - smartvillage-net

  frontend:
    build:
      context: ../website
      dockerfile: Dockerfile
    container_name: smartvillage-frontend
    volumes:
      - frontend-build:/usr/share/nginx/html
    networks:
      - smartvillage-net

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: smartvillage-backend
    depends_on:
      - postgres
    env_file:
    - /opt/smartvillage/smartvillage.env
    ports:
      - "8000:8000"
    networks:
      - smartvillage-net

  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: smartvillage-postgres
    env_file:
    - /opt/smartvillage/smartvillage.env
    volumes:
      - /srv/smartvillage/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - smartvillage-net

networks:
  smartvillage-net:

volumes:
  postgres-data:
  frontend-build:
