#!/usr/bin/env bash
set -e

MQTT_URL="mqtt://localhost:1883" \
ACCOUNT_ID=3 \
VILLAGE_ID=3 \
DEVICE_COUNT=3 \
MITFAHRBANK_COUNT=5 \
SCENARIO=2 \
DISCOVERY_ON_CONNECT=1 \
PUBLISH_INTERVAL_MS=5000 \
DEVICE_FAILURE_PROBABILITY=0.001 \
DEVICE_REVIVE_PROBABILITY=0.001 \
SENSOR_FAILURE_PROBABILITY=0.002 \
SENSOR_STUCK_PROBABILITY=0.002 \
npm run simulate:mitfahrbank
